### ISSUE TITLE
Release APK on Github or F-Droid

### ISSUE THREAD

**Issue by IzzySoft** [luankevinferreira/expenses#24]
Would you mind publishing your app on F-Droid (though Google Analytics would be a show-stopper there, so that would need a special flavour without GA) – or at least attaching the `.apk` to its corresponding `/releases`? Not everybody can/will use Playstore, so it'd be great to have an alternative.

**Comment by luankevinferreira** [comment]
This app it's already on Playstore, thank you for the tip, good to know 👍

**Comment by IzzySoft** [comment]
@luankevinferreira I know it's on Playstore. The reason I was asking, quoting myself:

> Not everybody can/will use Playstore, so it'd be great to have an alternative.

Guess it wouldn't be too hard attaching the `.apk` to the release. When in doubt, see the GitHub Help description in [Creating Releases](https://help.github.com/articles/creating-releases/). I you'd do it, I could make it available via [my repo](https://apt.izzysoft.de/fdroid) (the largest 3rd party F-Droid repo, second in size only to the official one, and quite well known :wink:) As I don't build myself (and prefer keeping your signature intact), I'd need the APK there for that.

**Comment by luankevinferreira** [comment]
Sorry @IzzySoft I had not understood correctly. So all that do I need to do it's attach the `.apk` on the correspondent release?

**Comment by IzzySoft** [comment]
That's it, yes – everything else you already have to do for the Playstore release anyway (making sure `versionCode` gets increased and `versionName` reflects the (user readable) version of the release. The latter best reflects the tag name, which you might wish to prefix with a `v` – not really required, but considered good practice). My auto-updater compares the tag name with the latest version present in the repo and, if the former is "higher" (and not marked "pre-release"), fetches that. Updates are usually available within 24h of your having the APK attached to a new tag.

As a note: that version comparison currently is alpha-numerical (due to the fact that some devs use crazy tag names) with the `v`-prefix stripped, so if you'd release v1.1.10 my updater would miss that (but catch up at 1.2.*). Sometimes users report that to me, and then I fetch those specific versions manually. Happens rarely enough, luckily.

So when the first APK is available that way, just drop me a note here in this issue and I initialize the record for your app.

**Comment by luankevinferreira** [comment]
Ok then, I will attach the APK on the next release 👍

**Comment by IzzySoft** [comment]
If you could attach the latest one (v1.1.6) already, I could setup the record as well (and it then fetches the next release automatically). Up to you, of course :wink:

**Comment by luankevinferreira** [comment]
Ok, then I will attach 😉

**Comment by luankevinferreira** [comment]
Done! Tell me if it's all right 😉

**Comment by IzzySoft** [comment]
Thanks, but unfortunately it's not:

```
ERROR: Failed to get apk information, skipping repo/luankevinferreira.expenses_v1.2.0.apk
WARNING: Skipping 'luankevinferreira.expenses_v1.2.0.apk' with invalid signature!
```

Not sure what it is; `apksigner verify` doesn't choke but `fdroidserver` is. Another error I get is:

```
ERROR getting 'android:icon' attribute: attribute is not a string value
```

Could you please check?

**PS:** It's the latter error causing the abort, thrown by `aapt dump badging`. So if you'll fix the icon error, it should be fine (and I'll retry then).

**Comment by luankevinferreira** [comment]
Can you try again?

**Comment by IzzySoft** [comment]
\o/ That worked out, thanks a lot! [See here](https://apt.izzysoft.de/fdroid/index/apk/luankevinferreira.expenses) – and feel free to point to that place for those (like me) preferring to use GPlay as little as possible :wink:

As I already wrote: Updates should appear there within 24h of your attaching the `.apk` to a new tag. If the APK has problems (like we just had it), the updater informs me and I'd contact you again. If you have any questions/issues with my repo (e.g. want the app description adjusted), feel free to ping me anytime.

Thanks again for your support!
